version: 0.2
        
phases:
  install:
    on-failure: ABORT 
    runtime-versions:
      php: 8.2
    commands:
      - echo 'install'
  pre_build:
    on-failure: ABORT 
    commands:
      - echo 'install'
  build:
    on-failure: ABORT
    commands:
      - echo 'build'
  post_build:
    on-failure: ABORT
    commands:
      - echo 'Post Build'