services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viralblog_appv2
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: virablog_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: viralblog
      MYSQL_ROOT_PASSWORD: viraladmin
      MYSQL_PASSWORD: viraladmin
      MYSQL_USER: viraladmin
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: viralblog_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: viraladmin
    depends_on:
      - db
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
